export const COMPANY_PREFIX = "RGOT";

export const ROLES = {
  MANAGER: "MANAGER",
  ADMIN: "ADMIN",
  EMPLOYEE: "EMPLOYEE",
};

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

export const EMPLOYMENT_TYPES = {
  FULL_TIME: "FULL_TIME",
  CONTRACT: "CONTRACT",
  INTERN: "INTERN",
};

export const PAYROLL_TYPES = {
  MONTHLY: "MONTHLY",
  WEEKLY: "WEEKLY",
};

export const DEVICE_TYPES = {
  WEB: "web",
  MOBILE: "mobile",
};

export const ACCRUAL_TYPES = {
  NONE: "NONE",
  YEARLY: "YEARLY",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
};

export const LEAVE_TYPE_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

export const HOLIDAY_TYPES = {
  PUBLIC: "PUBLIC",
  RESTRICTED: "RESTRICTED",
  OPTIONAL: "OPTIONAL",
};

export const LEAVE_REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const HALF_DAY_PERIODS = {
  FIRST_HALF: "FIRST_HALF",
  SECOND_HALF: "SECOND_HALF",
};

export const LEAVE_REQUEST_ACTION = {
  APPROVE: "APPROVE",
  REJECT: "REJECT",
};

export const EMAIL_ACTION_TOKEN_STATUS = {
  PENDING: "PENDING",
  USED: "USED",
  EXPIRED: "EXPIRED",
};
